EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Area_de_estudio__c.field-meta.xml
<CustomField>
    <fullName>Area_de_estudio__c</fullName>
    <label>Area de estudio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIENCIAS DE LA SALUD</fullName>
            </value>
            <value>
                <fullName>CIENCIAS SOCIALES Y HUMANIDADES</fullName>
            </value>
            <value>
                <fullName>INGENIERIA Y SISTEMAS</fullName>
            </value>
            <value>
                <fullName>NEGOCIOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Jornada__c.field-meta.xml
<CustomField>
    <fullName>Jornada__c</fullName>
    <label>Jornada</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN LINEA</fullName>
            </value>
            <value>
                <fullName>FIN DE SEMANA</fullName>
            </value>
            <value>
                <fullName>MATUTINO</fullName>
            </value>
            <value>
                <fullName>NOCTURNO</fullName>
            </value>
            <value>
                <fullName>SABATINO</fullName>
            </value>
            <value>
                <fullName>VESPERTINO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRESENCIAL</fullName>
            </value>
            <value>
                <fullName>VIRTUAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Nivel_de_estudio__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_estudio__c</fullName>
    <label>Nivel de estudio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepa UMM</fullName>
            </value>
            <value>
                <fullName>Profesional</fullName>
            </value>
            <value>
                <fullName>Maestria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Programa_largo__c.field-meta.xml
<CustomField>
    <fullName>Programa_largo__c</fullName>
    <label>Programa largo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <label>Sede</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Site</valueSetName>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Term__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</description>
    <inlineHelpText>El Programa académico, Departamento o Institución educativa al que se aplica este plazo. Seleccione la cuenta que representa su Institución educativa si los plazos son coherentes en todos los Programas y Departamentos de su escuela.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presencial</fullName>
            </value>
            <value>
                <fullName>En línea</fullName>
            </value>
            <value>
                <fullName>Híbrido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Periodo__c.field-meta.xml
<CustomField>
    <fullName>Periodo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Periodo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.hed__Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Programa_Acad_mico__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Programa_Acad_mico__c.field-meta.xml
<CustomField>
    <fullName>Programa_Acad_mico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa Académico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Academic_Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/classes/SolicitarInfoControllerTest.cls
@isTest
public class SolicitarInfoControllerTest {
    @isTest static void testSaveAcc() {
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:email','luis.torres@mail.com');
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'Test';       
        acc.Programa_largo__c = 'Test a';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA';
        acc.Jornada__c = 'Fin de semana';
        insert acc;
        
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa', acc.Id);
        
        Account alu = new Account();
        alu.Name = 'test';
        alu.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household Account').getRecordTypeId();
        insert alu;
        
        Contact cont = new Contact();
        cont.LastName = 'test1';
        cont.Email = 'test@test.com';
        cont.AccountId = alu.Id;
        cont.Nacionalidad__c = 'Mexicana';
        insert cont;
        
        hed__Term__c per = new hed__Term__c();
        per.name = 'test';
        per.hed__Account__c = acc.Id;
        insert per;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'opp';
        opp.StageName = 'Abierto';
        opp.CloseDate = System.today() + 1;
        opp.AccountId = alu.Id;
        opp.ContactId = cont.Id;
        opp.Programa_Acad_mico__c = acc.Id;
        opp.Periodo__c = per.Id;
        insert opp;
        
        ummctrl.Nivel_de_Estudio = 'PREGRADO';
        ummctrl.Area_de_Estudio = '';
        ummctrl.source = '';
        ummctrl.Household = alu;
        ummctrl.formModalidad = 'PRESENCIAL';
        ummctrl.formSede = 'APODACA';
        ummctrl.formSite = 'APODACA';
        PageReference controller = ummctrl.saveAccount();
        System.assert(true);    
    }
    
    @isTest static void testNivelEstudio() {
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getNiveldeEstudio();
        System.assert(controller != null); 
    }
    
    @isTest static void testNivelEstudio2() {
        PageReference pageRef = Page.SolicitarInfoForm;
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa','82');
        /*Programa__c programa = new Programa__c();
        programa.Nivel_de_Estudio__c = 'Profesional';
        programa.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        programa.Codigo_programa__c = '82';
        programa.Tipo_de_programa__c = 'PREGRADO';
        programa.Activo__c = true;
        insert programa;*/
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';       
        acc.Programa_largo__c = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA';
        acc.Jornada__c = 'Fin de semana';
        acc.Nivel_de_estudio__c = 'Profesional';
        insert acc;
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getNiveldeEstudio();
        System.assert(controller != null); 
    }
    
    @isTest static void testProgramas() {
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:nivelDeEstudio','POSGRADO');
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getProgramas();
        System.assert(controller != null); 
    }
    
    @isTest static void testProgramas1() {
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:nivelDeEstudio','PREGRADO');
        /*Programa__c programa = new Programa__c();
        programa.Nivel_de_Estudio__c = 'Profesional';
        programa.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        programa.Activo__c = true;
        programa.Codigo_programa__c = '52';
        insert programa;*/
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';       
        acc.Programa_largo__c = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA';
        acc.Jornada__c = 'Fin de semana';
        acc.Nivel_de_estudio__c = 'Profesional';
        insert acc;
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getProgramas();
        System.assert(controller != null); 
    }
    
    @isTest static void testProgramas2() {
        PageReference pageRef = Page.SolicitarInfoForm;
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa','82');
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:nivelDeEstudio','BACHILLERATO');
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getProgramas();
        System.assert(controller != null); 
    }
    
    @isTest static void testAreadeEstudio() {
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getAreadeEstudio();
        System.assert(controller != null); 
    }
    
    @isTest static void testAreadeEstudio2() {
        PageReference pageRef = Page.SolicitarInfoForm;
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa','82');
        /*Programa__c programa = new Programa__c();
        programa.Nivel_de_Estudio__c = 'Profesional';
        programa.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        programa.Codigo_programa__c = '82';
        programa.Area_de_Estudio__c = 'NEGOCIOS';
        programa.Activo__c = true;
        insert programa;*/
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';       
        acc.Programa_largo__c = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA';
        acc.Jornada__c = 'Fin de semana';
        acc.Nivel_de_estudio__c = 'Profesional';
        insert acc;
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getAreadeEstudio();
        System.assert(controller != null); 
    }
    
    @isTest static void testModalidades() {
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getModalidades();
        System.assert(controller != null); 
    }
    
    @isTest static void testModalidades2() {
        PageReference pageRef = Page.SolicitarInfoForm;
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa','82');
        /*Programa__c programa = new Programa__c();
        programa.Nivel_de_Estudio__c = 'Profesional';
        programa.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        programa.Codigo_programa__c = '82';
        programa.Modalidad__c = 'PRESENCIAL';
        programa.Activo__c = true;
        insert programa;    */ 
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';       
        acc.Programa_largo__c = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA';
        acc.Jornada__c = 'Fin de semana';
        acc.Nivel_de_estudio__c = 'Profesional';
        insert acc;
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getModalidades();
        System.assert(controller != null); 
    }
    
    @isTest static void testSedes() {
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getSedes();
        System.assert(controller != null); 
    }
    
    @isTest static void testSedes2() {
        PageReference pageRef = Page.SolicitarInfoForm;
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa','82');
        /*Programa__c programa = new Programa__c();
        programa.Nivel_de_Estudio__c = 'Profesional';
        programa.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        programa.Codigo_programa__c = '82';
        programa.Sede__c = 'APODACA;CENTRO;SANTA CATARINA';
        programa.Activo__c = true;
        insert programa;*/
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';       
        acc.Programa_largo__c = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA;CENTRO';
        acc.Jornada__c = 'Fin de semana';
        acc.Nivel_de_estudio__c = 'Profesional';
        insert acc;
        
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa', acc.Id);
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getSedes();
        System.assert(controller != null); 
    }
    
    @isTest static void testSites() {
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getSite();
        System.assert(controller != null); 
    }
    
    @isTest static void testSites2() {
        PageReference pageRef = Page.SolicitarInfoForm;
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa','82');
        /*Programa__c programa = new Programa__c();
        programa.Nivel_de_Estudio__c = 'Profesional';
        programa.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        programa.Codigo_programa__c = '82';
        programa.Sede__c = 'APODACA;CENTRO;SANTA CATARINA';
        programa.Activo__c = true;
        insert programa;*/
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'LIC. ADMINISTRACION DE EMPRESAS 2015';       
        acc.Programa_largo__c = 'LIC. ADMINISTRACION DE EMPRESAS 2015';
        acc.Modalidad__c = 'VIRTUAL';
        acc.Site__c = 'APODACA;CENTRO';
        acc.Jornada__c = 'Fin de semana';
        acc.Nivel_de_estudio__c = 'Profesional';
        insert acc;
        
        ApexPages.currentPage().getParameters().put('j_id0:j_id2:formulario:programa', acc.Id);
        
        SolicitarInfoController ummctrl = new SolicitarInfoController();
        List<SelectOption> controller = ummctrl.getSite();
        System.assert(controller != null); 
    }
}