EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Jornada__c.field-meta.xml
<CustomField>
    <fullName>Jornada__c</fullName>
    <label>Jornada</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN LINEA</fullName>
            </value>
            <value>
                <fullName>FIN DE SEMANA</fullName>
            </value>
            <value>
                <fullName>MATUTINO</fullName>
            </value>
            <value>
                <fullName>NOCTURNO</fullName>
            </value>
            <value>
                <fullName>SABATINO</fullName>
            </value>
            <value>
                <fullName>VESPERTINO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRESENCIAL</fullName>
            </value>
            <value>
                <fullName>VIRTUAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Nivel_de_estudio__c.field-meta.xml
<CustomField>
    <fullName>Nivel_de_estudio__c</fullName>
    <label>Nivel de estudio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prepa UMM</fullName>
            </value>
            <value>
                <fullName>Profesional</fullName>
            </value>
            <value>
                <fullName>Maestria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Programa_largo__c.field-meta.xml
<CustomField>
    <fullName>Programa_largo__c</fullName>
    <label>Programa largo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <label>Sede</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Site</valueSetName>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/CURP__c.field-meta.xml
<CustomField>
    <fullName>CURP__c</fullName>
    <label>CURP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Email_del_tutor__c.field-meta.xml
<CustomField>
    <fullName>Email_del_tutor__c</fullName>
    <label>Email del tutor</label>
    <type>Email</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Escuela_de_procedencia__c.field-meta.xml
<CustomField>
    <fullName>Escuela_de_procedencia__c</fullName>
    <label>Escuela de procedencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Divorcio</fullName>
            </value>
            <value>
                <fullName>Soltero</fullName>
            </value>
            <value>
                <fullName>Viudo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Nombre_del_tutor__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_tutor__c</fullName>
    <label>Nombre del tutor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Primer_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Primer_Apellido__c</fullName>
    <label>Primer Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Segundo_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Segundo_Apellido__c</fullName>
    <label>Segundo Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hombre</fullName>
            </value>
            <value>
                <fullName>Mujer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Telefono_del_tutor__c.field-meta.xml
<CustomField>
    <fullName>Telefono_del_tutor__c</fullName>
    <label>Teléfono del tutor</label>
    <type>Phone</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/CURP__c.field-meta.xml
<CustomField>
    <fullName>CURP__c</fullName>
    <label>CURP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Email_del_tutor__c.field-meta.xml
<CustomField>
    <fullName>Email_del_tutor__c</fullName>
    <label>Email del tutor</label>
    <type>Email</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Escuela_de_procedencia__c.field-meta.xml
<CustomField>
    <fullName>Escuela_de_procedencia__c</fullName>
    <label>Escuela de procedencia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <label>Estado civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casado</fullName>
            </value>
            <value>
                <fullName>Divorcio</fullName>
            </value>
            <value>
                <fullName>Soltero</fullName>
            </value>
            <value>
                <fullName>Viudo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The term when the applicant wants to enroll.</description>
    <inlineHelpText>El plazo en el que el solicitante desea inscribirse.</inlineHelpText>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mexicana</fullName>
            </value>
            <value>
                <fullName>Extranjero</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Nombre_del_alumno__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_alumno__c</fullName>
    <label>Nombre del alumno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Nombre_del_tutor__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_tutor__c</fullName>
    <label>Nombre del tutor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solicitudes</relationshipLabel>
    <relationshipName>Solicitudes</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/PersonBirthdate__c.field-meta.xml
<CustomField>
    <fullName>PersonBirthdate__c</fullName>
    <label>Fecha de nacimiento</label>
    <type>Date</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Primer_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Primer_Apellido__c</fullName>
    <label>Primer Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Segundo_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Segundo_Apellido__c</fullName>
    <label>Segundo Apellido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mujer</fullName>
            </value>
            <value>
                <fullName>Hombre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/ShippingCity__c.field-meta.xml
<CustomField>
    <fullName>ShippingCity__c</fullName>
    <label>Ciudad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/ShippingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode__c</fullName>
    <label>Codigo postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/ShippingState__c.field-meta.xml
<CustomField>
    <fullName>ShippingState__c</fullName>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/ShippingStreet__c.field-meta.xml
<CustomField>
    <fullName>ShippingStreet__c</fullName>
    <label>Calle, No. y Colonia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Application__c/fields/Telefono_del_tutor__c.field-meta.xml
<CustomField>
    <fullName>Telefono_del_tutor__c</fullName>
    <label>Telefono del tutor</label>
    <type>Phone</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Term__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</description>
    <inlineHelpText>El Programa académico, Departamento o Institución educativa al que se aplica este plazo. Seleccione la cuenta que representa su Institución educativa si los plazos son coherentes en todos los Programas y Departamentos de su escuela.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presencial</fullName>
            </value>
            <value>
                <fullName>En línea</fullName>
            </value>
            <value>
                <fullName>Híbrido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Programa_Acad_mico__c.field-meta.xml
<CustomField>
    <fullName>Programa_Acad_mico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa Académico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Academic_Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/classes/InscripcionesFormController.cls
public without sharing class InscripcionesFormController {
    public Contact alu {get;set;}
    public Opportunity opp {get;set;}
    public List<SelectOption> niveles {get;set;}
    public List<SelectOption> sedes {get;set;}
    public List<SelectOption> sites {get;set;}
    public List<SelectOption> turnos {get;set;}
    public List<SelectOption> programas {get;set;}
    public List<SelectOption> estadociviles {get;set;}
    public List<SelectOption> nacionalidades {get;set;}
    public List<SelectOption> sexos {get;set;}
    public List<SelectOption> billingstates {get;set;}
    public Account programaSelected {get;set;}
    public Boolean esVirtual {get;set;}
    public Id oppId {get;set;}
    public Id ProgRTId {get;set;}
    
    public String FirstName {get;set;}
    public String ApellidoPaterno {get;set;}
    public String ApellidoMaterno {get;set;}
    public String Nombredeltutorc {get;set;}
    public String Emaildeltutorc {get;set;}
    public String Telefonodeltutorc {get;set;}
    public String PersonMobilePhone {get;set;}
    public String PersonEmail {get;set;}
    public String Nacionalidadc {get;set;}
    public String CURPc {get;set;}
    public String EstadoCivilc {get;set;}
    public String Sexoc {get;set;}
    public Date PersonBirthdate {get;set;}
    public Boolean MayorDeEdad {get;set;}
    public String DiaNacimiento {get;set;}
    public List<SelectOption> dias {get;set;}
    public String MesNacimiento {get;set;}
    public List<SelectOption> meses {get;set;}
    public String AnoNacimiento {get;set;}
    public List<SelectOption> anos {get;set;}
    public String Calle {get;set;}
    public String Numero {get;set;}
    public String Colonia {get;set;}
    public String BillingCity {get;set;}
    public String BillingState {get;set;}
    public String BillingPostalCode {get;set;}
    public String Escueladeprocedenciac {get;set;}
    
    public String Tipodecarrerac {get;set;}
    public String Programac {get;set;}
    public hed__Term__c Plazo {get;set;}
    public String Modalidadc {get;set;}
    public String Sedec {get;set;}
    public String Sitec {get;set;}
    public String Jornadac {get;set;}
    public String Aceptterminosc {get;set;}
    
    public Boolean HayErrores {get;set;}
    
    public InscripcionesFormController(){
        ProgRTId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        MayorDeEdad = false;
        HayErrores = false;
        oppId = apexpages.currentpage().getparameters().get('id');
        niveles = new List<SelectOption>();
        niveles.add(new SelectOption('Prepa UMM','Prepa UMM'));
        niveles.add(new SelectOption('Profesional','Profesional'));
        niveles.add(new SelectOption('Posgrado','Maestria'));

        opp = [select ContactId, Programa_Acad_mico__c from Opportunity where id =: oppId];
        alu = [select Name, FirstName, LastName, Phone, Email, Nacionalidad__c, CURP__c, Estado_Civil__c, Sexo__c, Birthdate, MailingStreet, MailingCity, 
               MailingState, MailingPostalCode, Escuela_de_procedencia__c,  Email_del_tutor__c, Nombre_del_tutor__c, Telefono_del_tutor__c, Primer_Apellido__c, Segundo_Apellido__c              
              from Contact
              where id =: opp.ContactId LIMIT 1];
        ProgramaSelected = [select nivel_de_estudio__c, programa_largo__c, sede__c, site__c, jornada__c, modalidad__c from Account where Id =: opp.Programa_Acad_mico__c];
        
        FirstName = alu.FirstName;
        ApellidoPaterno = alu.Primer_Apellido__c;
        ApellidoMaterno = alu.Segundo_Apellido__c;
        Nombredeltutorc = alu.Nombre_del_tutor__c;
        Emaildeltutorc = alu.Email_del_tutor__c;
        Telefonodeltutorc = alu.Telefono_del_tutor__c;
        PersonMobilePhone = alu.Phone;
        PersonEmail = alu.Email;
        Nacionalidadc = alu.Nacionalidad__c;
        CURPc = alu.CURP__c;
        EstadoCivilc = alu.Estado_Civil__c;
        Sexoc = alu.Sexo__c;
        PersonBirthdate = alu.Birthdate;
        Calle = alu.MailingStreet;
        BillingCity = alu.MailingCity;
        BillingState = alu.MailingState;
        BillingPostalCode = alu.MailingPostalCode;
        Escueladeprocedenciac = alu.Escuela_de_procedencia__c;
        
        sedec = ProgramaSelected.Sede__c;
        sitec = ProgramaSelected.Site__c;
        jornadac = ProgramaSelected.Jornada__c;
        
        
        
        
        sedes = new List<SelectOption>();
        sites = new List<SelectOption>();
        turnos = new List<SelectOption>();
        estadociviles = new List<SelectOption>();
        sexos = new List<SelectOption>();
        billingstates = new List<SelectOption>();
        nacionalidades = new List<SelectOption>();
        
        estadociviles.add(new SelectOption('','--Selecciona un estado civil--'));
        estadociviles.add(new SelectOption('Casado','Casado'));
        estadociviles.add(new SelectOption('Divorcio','Divorcio'));
        estadociviles.add(new SelectOption('Soltero','Soltero'));
        estadociviles.add(new SelectOption('Viudo','Viudo'));
        
        sexos.add(new SelectOption('Mujer','Mujer'));
        sexos.add(new SelectOption('Hombre','Hombre'));
        
        nacionalidades.add(new SelectOption('Mexicana','Mexicana'));
        nacionalidades.add(new SelectOption('Extranjero','Extranjero'));

		billingstates.add(new SelectOption('Aguascalientes','Aguascalientes'));        
        billingstates.add(new SelectOption('Baja California','Baja California'));
        billingstates.add(new SelectOption('Baja California Sur','Baja California Sur'));
        billingstates.add(new SelectOption('Campeche','Campeche'));
        billingstates.add(new SelectOption('Chiapas','Chiapas'));
        billingstates.add(new SelectOption('Chihuahua','Chihuahua'));        
        billingstates.add(new SelectOption('Ciudad de México','Ciudad de México'));
        billingstates.add(new SelectOption('Coahuila','Coahuila'));
        billingstates.add(new SelectOption('Colima','Colima'));
        billingstates.add(new SelectOption('Durango','Durango'));
        billingstates.add(new SelectOption('Guanajuato','Guanajuato'));        
        billingstates.add(new SelectOption('Guerrero','Guerrero'));
        billingstates.add(new SelectOption('Hidalgo','Hidalgo'));
        billingstates.add(new SelectOption('Jalisco','Jalisco'));
        billingstates.add(new SelectOption('México','México'));
        billingstates.add(new SelectOption('Michoacán','Michoacán'));        
        billingstates.add(new SelectOption('Morelos','Morelos'));
        billingstates.add(new SelectOption('Nayarit','Nayarit'));
        billingstates.add(new SelectOption('Nuevo León','Nuevo León'));
        billingstates.add(new SelectOption('Oaxaca','Oaxaca'));
        billingstates.add(new SelectOption('Puebla','Puebla'));        
        billingstates.add(new SelectOption('Querétaro','Querétaro'));
        billingstates.add(new SelectOption('Quintana Roo','Quintana Roo'));
        billingstates.add(new SelectOption('San Luis Potosí','San Luis Potosí'));
        billingstates.add(new SelectOption('Sinaloa','Sinaloa'));
        billingstates.add(new SelectOption('Sonora','Sonora'));        
        billingstates.add(new SelectOption('Tabasco','Tabasco'));
        billingstates.add(new SelectOption('Tamaulipas','Tamaulipas'));
        billingstates.add(new SelectOption('Tlaxcala','Tlaxcala'));
        billingstates.add(new SelectOption('Veracruz','Veracruz'));
        billingstates.add(new SelectOption('Yucatán','Yucatán'));
        billingstates.add(new SelectOption('Zacatecas','Zacatecas'));
        
        
        
        
        Tipodecarrerac = ProgramaSelected.Nivel_de_estudio__c;
        getProgramas(Tipodecarrerac);        
        Programac = ProgramaSelected.id;
        Plazo = [SELECT Id FROM hed__Term__c WHERE hed__Account__c =: ProgramaSelected.Id];
        Modalidadc = ProgramaSelected.Modalidad__c;
        SelectPrograma();
        if(PersonBirthdate != null){
            MayorDeEdad = System.today().year() - PersonBirthdate.year() > 17;
        }
    }
    
    
    public PageReference Registrar(){
        System.debug('Validando edad');
        MayorDeEdad = System.today().year() - PersonBirthdate.year() > 17;
        if(!MayorDeEdad && Nombredeltutorc == '' && Emaildeltutorc == '' && Telefonodeltutorc == ''){
            return null;
        }
        if(!Boolean.valueOf(Aceptterminosc)){
            HayErrores = true;
            return null;
        }
        
        HayErrores = false;
        hed__Application__c app = new hed__Application__c();
        app.Opportunity__c = opp.Id;
        app.FirstName__c = FirstName;
        app.Primer_Apellido__c = ApellidoPaterno;
        app.Segundo_Apellido__c = ApellidoMaterno;
        app.Nombre_del_alumno__c = FirstName + ' ' + ApellidoPaterno + ' ' + ApellidoMaterno;
        app.Celular__c = PersonMobilePhone;
        app.Correo_electronico__c = PersonEmail;
        app.Nombre_del_tutor__c = Nombredeltutorc;
        app.Email_del_tutor__c = Emaildeltutorc;
        app.Telefono_del_tutor__c = Telefonodeltutorc;
        app.Nacionalidad__c = Nacionalidadc;
        app.CURP__c = CURPc;
        app.Estado_Civil__c = EstadoCivilc;
        app.Sexo__c = Sexoc;
        app.PersonBirthdate__c = PersonBirthdate;
        app.ShippingStreet__c = Calle;
        app.ShippingCity__c = BillingCity;
        app.ShippingState__c = BillingState;
        app.ShippingPostalCode__c = BillingPostalCode;
        app.Direccion__c = Calle + ', ' + BillingPostalCode + ', ' + BillingCity + ', ' + BillingState;
        app.Escuela_de_procedencia__c = Escueladeprocedenciac;
        app.Nivel_Escolar__c = ProgramaSelected.Nivel_de_estudio__c;
        app.hed__Applying_To__c = ProgramaSelected.Id;
        app.hed__Applicant__c = alu.Id;
        
                
        insert app;
        if(Test.isRunningTest()){
            return null;
        }
        
        return null;//new PageReference('https://www.umm.edu.mx/landings/il/gracias/');
    }
    
    public void SelectNivel(){
        System.debug('Se selecciono el nivel: ' + Tipodecarrerac);
        ResetLists();
        getProgramas(Tipodecarrerac);
    }
	
    public void SelectPrograma(){
		System.debug('Programa seleccionado: ' + Programac);
		programaSelected = [Select id, Nivel_de_estudio__c, Programa_largo__c, Modalidad__c, Sede__c, Site__c, Jornada__c from Account where Id =: Programac];
        if(programaSelected.Modalidad__c == 'PRESENCIAL'){
            esVirtual = false;
            getSede();
        }else{
            esVirtual = true;
            getSite();
        }
        getTurno();
        Programac = programaSelected.Id;
        Plazo = [SELECT Id FROM hed__Term__c WHERE hed__Account__c =: ProgramaSelected.Id];
        Modalidadc = programaSelected.Modalidad__c;
    }
	    
    public void getProgramas(String nivel){
        programas = new List<SelectOption>();
        List<Account> progs = [Select id, name, Programa_largo__c from Account Where Nivel_de_estudio__c =: nivel AND RecordtypeId =: ProgRTId];
        programas.add(new SelectOption('','--Selecciona un programa--'));
        if(progs.size()>0){
        	for(Account prog : progs){
            	programas.add(new SelectOption(prog.Id, prog.Programa_largo__c));
        	}
        }
    }
    
    public void getSede(){
        sedes = new List<SelectOption>();
        sedes.add(new SelectOption('','--Selecciona una sede--'));
        List<String> temp = new List<String>();
        temp.addAll(programaSelected.Sede__c.split(';'));
        System.debug(temp);
        for(String sede : temp){
            sedes.add(new SelectOption(sede,sede));
        }
    }
    
    public void getSite(){
        sites = new List<SelectOption>();
        sites.add(new SelectOption('','--Selecciona un site--'));
        List<String> temp = new List<String>();
        temp.addAll(programaSelected.Site__c.split(';'));
        System.debug(temp);
        for(String site : temp){
            sites.add(new SelectOption(site,site));
        }
    }
    
    public void getTurno(){
        turnos = new List<SelectOption>();
        turnos.add(new SelectOption('','--Selecciona un turno--'));
        List<String> temp = new List<String>();
        temp.addAll(programaSelected.Jornada__c.split(';'));
        System.debug(temp);
        for(String jornada : temp){
            turnos.add(new SelectOption(jornada,jornada));
        }
    }
    public void ResetLists(){
        sedes = new List<SelectOption>();
        sites = new List<SelectOption>();
        turnos = new List<SelectOption>();
        
        sedes.add(new SelectOption('','--Selecciona un programa--'));
        sites.add(new SelectOption('','--Selecciona un programa--'));
        turnos.add(new SelectOption('','--Selecciona un programa--'));
    }
}