EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Jornada__c.field-meta.xml
<CustomField>
    <fullName>Jornada__c</fullName>
    <label>Jornada</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN LINEA</fullName>
            </value>
            <value>
                <fullName>FIN DE SEMANA</fullName>
            </value>
            <value>
                <fullName>MATUTINO</fullName>
            </value>
            <value>
                <fullName>NOCTURNO</fullName>
            </value>
            <value>
                <fullName>SABATINO</fullName>
            </value>
            <value>
                <fullName>VESPERTINO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRESENCIAL</fullName>
            </value>
            <value>
                <fullName>VIRTUAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Programa_largo__c.field-meta.xml
<CustomField>
    <fullName>Programa_largo__c</fullName>
    <label>Programa largo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Account/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <label>Sede</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Contact/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/hed__Term__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</description>
    <inlineHelpText>El Programa académico, Departamento o Institución educativa al que se aplica este plazo. Seleccione la cuenta que representa su Institución educativa si los plazos son coherentes en todos los Programas y Departamentos de su escuela.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Modalidad__c.field-meta.xml
<CustomField>
    <fullName>Modalidad__c</fullName>
    <label>Modalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presencial</fullName>
            </value>
            <value>
                <fullName>En línea</fullName>
            </value>
            <value>
                <fullName>Híbrido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Periodo__c.field-meta.xml
<CustomField>
    <fullName>Periodo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Periodo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.hed__Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Programa_Acad_mico__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/objects/Opportunity/fields/Programa_Acad_mico__c.field-meta.xml
<CustomField>
    <fullName>Programa_Acad_mico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programa Académico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Academic_Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

EDAUMMSandbox/EDAUMMSandbox/force-app/main/default/classes/InscripcionesFormControllerTest.cls
@IsTest
public class InscripcionesFormControllerTest {
	@IsTest public static void testInscripcion(){
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Name = 'Test';       
        acc.Programa_largo__c = 'Test a';
        acc.Modalidad__c = 'PRESENCIAL';
        acc.Sede__c = 'APODACA';
        acc.Jornada__c = 'Fin de semana';
        insert acc;
        
        Account alu = new Account();
        alu.Name = 'test';
        alu.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household Account').getRecordTypeId();
        insert alu;
        
        Contact cont = new Contact();
        cont.LastName = 'test1';
        cont.Email = 'test@test.com';
        cont.AccountId = alu.Id;
        cont.Nacionalidad__c = 'Mexicana';
        insert cont;
        
        hed__Term__c per = new hed__Term__c();
        per.name = 'test';
        per.hed__Account__c = acc.Id;
        insert per;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'opp';
        opp.StageName = 'Abierto';
        opp.CloseDate = System.today() + 1;
        opp.AccountId = alu.Id;
        opp.ContactId = cont.Id;
        opp.Programa_Acad_mico__c = acc.Id;
        opp.Periodo__c = per.Id;
        insert opp;
        
        
        
        Test.startTest();
        
        Test.setCurrentPageReference(new PageReference('Page.InscripcionesForm')); 
        System.currentPageReference().getParameters().put('id', opp.Id);
        InscripcionesFormController FP = new InscripcionesFormController();
        FP.ApellidoPaterno = 'test';
        FP.ApellidoMAterno = 'test';
        FP.DiaNacimiento = '1';
        FP.MesNacimiento = '1';
        FP.AnoNacimiento = '1995';
        FP.Nombredeltutorc = 'test';
        FP.Emaildeltutorc = 'test@test.com';
        FP.Telefonodeltutorc = '8';
        FP.PersonMobilePhone = '8';
        FP.PersonEmail = 'test@test.com';
        FP.Nacionalidadc = 'Mexicana';
        FP.CURPc = 'test';
        FP.EstadoCivilc = 'casado';
        FP.PersonBirthdate = Date.newInstance(2000, 12, 9);
        FP.Calle = 'test';
        FP.BillingCity = 'test';
        FP.BillingState = 'test';
        FP.BillingPostalCode = 'test';
        FP.Escueladeprocedenciac = 'test';
        
        FP.Tipodecarrerac = 'Prepa UMM';
    	FP.Programac = acc.Id;
    	FP.Sedec = 'APODACA';
    	FP.Sitec = '';
   		FP.Jornadac = 'MATUTINO';
    	FP.Aceptterminosc = 'true';
        
        FP.Registrar();
        FP.ResetLists();
        
        Test.stopTest();
    }
}